    const followersMock = [
    {
      login: "sudo-bluee",
      id: 22403506,
      node_id: "MDQ6VXNlcjIyNDAzNTA2",
      avatar_url: "https://avatars.githubusercontent.com/u/22403506?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/sudo-bluee",
      html_url: "https://github.com/sudo-bluee",
      followers_url: "https://api.github.com/users/sudo-bluee/followers",
      following_url: "https://api.github.com/users/sudo-bluee/following{/other_user}",
      gists_url: "https://api.github.com/users/sudo-bluee/gists{/gist_id}",
      starred_url: "https://api.github.com/users/sudo-bluee/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/sudo-bluee/subscriptions",
      organizations_url: "https://api.github.com/users/sudo-bluee/orgs",
      repos_url: "https://api.github.com/users/sudo-bluee/repos",
      events_url: "https://api.github.com/users/sudo-bluee/events{/privacy}",
      received_events_url: "https://api.github.com/users/sudo-bluee/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "Lasgiddys",
      id: 9812494228,
      node_id: "U_kgDOBdpTNA",
      avatar_url: "https://avatars.githubusercontent.com/u/98194228?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Lasgiddys",
      html_url: "https://github.com/Lasgiddystertreterterutyuty",
      followers_url: "https://api.github.com/users/Lasgiddys/followers",
      following_url: "https://api.github.com/users/Lasgiddys/following{/other_user}",
      gists_url: "https://api.github.com/users/Lasgiddys/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Lasgiddys/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Lasgiddys/subscriptions",
      organizations_url: "https://api.github.com/users/Lasgiddys/orgs",
      repos_url: "https://api.github.com/users/Lasgiddys/repos",
      events_url: "https://api.github.com/users/Lasgiddys/events{/privacy}",
      received_events_url: "https://api.github.com/users/Lasgiddys/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "sudo-bluee",
      id: 224345603506,
      node_id: "MDQ6VXNlcjIyNDAzNTA2",
      avatar_url: "https://avatars.githubusercontent.com/u/22403506?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/sudo-bluee",
      html_url: "https://github.com/sudo-bluee",
      followers_url: "https://api.github.com/users/sudo-bluee/followers",
      following_url: "https://api.github.com/users/sudo-bluee/following{/other_user}",
      gists_url: "https://api.github.com/users/sudo-bluee/gists{/gist_id}",
      starred_url: "https://api.github.com/users/sudo-bluee/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/sudo-bluee/subscriptions",
      organizations_url: "https://api.github.com/users/sudo-bluee/orgs",
      repos_url: "https://api.github.com/users/sudo-bluee/repos",
      events_url: "https://api.github.com/users/sudo-bluee/events{/privacy}",
      received_events_url: "https://api.github.com/users/sudo-bluee/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "Lasgiddys",
      id: 9819487228,
      node_id: "U_kgDOBdpTNA",
      avatar_url: "https://avatars.githubusercontent.com/u/98194228?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Lasgiddys",
      html_url: "https://github.com/Lasgiddystertreterterutyuty",
      followers_url: "https://api.github.com/users/Lasgiddys/followers",
      following_url: "https://api.github.com/users/Lasgiddys/following{/other_user}",
      gists_url: "https://api.github.com/users/Lasgiddys/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Lasgiddys/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Lasgiddys/subscriptions",
      organizations_url: "https://api.github.com/users/Lasgiddys/orgs",
      repos_url: "https://api.github.com/users/Lasgiddys/repos",
      events_url: "https://api.github.com/users/Lasgiddys/events{/privacy}",
      received_events_url: "https://api.github.com/users/Lasgiddys/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "sudo-bluee",
      id: 2240336545506,
      node_id: "MDQ6VXNlcjIyNDAzNTA2",
      avatar_url: "https://avatars.githubusercontent.com/u/22403506?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/sudo-bluee",
      html_url: "https://github.com/sudo-bluee",
      followers_url: "https://api.github.com/users/sudo-bluee/followers",
      following_url: "https://api.github.com/users/sudo-bluee/following{/other_user}",
      gists_url: "https://api.github.com/users/sudo-bluee/gists{/gist_id}",
      starred_url: "https://api.github.com/users/sudo-bluee/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/sudo-bluee/subscriptions",
      organizations_url: "https://api.github.com/users/sudo-bluee/orgs",
      repos_url: "https://api.github.com/users/sudo-bluee/repos",
      events_url: "https://api.github.com/users/sudo-bluee/events{/privacy}",
      received_events_url: "https://api.github.com/users/sudo-bluee/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "Lasgiddys",
      id: 98192544453228,
      node_id: "U_kgDOBdpTNA",
      avatar_url: "https://avatars.githubusercontent.com/u/98194228?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Lasgiddys",
      html_url: "https://github.com/Lasgiddystertreterterutyuty",
      followers_url: "https://api.github.com/users/Lasgiddys/followers",
      following_url: "https://api.github.com/users/Lasgiddys/following{/other_user}",
      gists_url: "https://api.github.com/users/Lasgiddys/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Lasgiddys/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Lasgiddys/subscriptions",
      organizations_url: "https://api.github.com/users/Lasgiddys/orgs",
      repos_url: "https://api.github.com/users/Lasgiddys/repos",
      events_url: "https://api.github.com/users/Lasgiddys/events{/privacy}",
      received_events_url: "https://api.github.com/users/Lasgiddys/received_events",
      type: "User",
      site_admin: false
    },
  ]

  export default followersMock;