export default {
    login: "anesdiaf",
    id: 10120682,
    node_id: "MDQ6VXNlcjEwMTIwNjgy",
    avatar_url: "https://avatars.githubusercontent.com/u/10120682?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/anesdiaf",
    html_url: "https://github.com/anesdiaf",
    followers_url: "https://api.github.com/users/anesdiaf/followers",
    following_url: "https://api.github.com/users/anesdiaf/following{/other_user}",
    gists_url: "https://api.github.com/users/anesdiaf/gists{/gist_id}",
    starred_url: "https://api.github.com/users/anesdiaf/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/anesdiaf/subscriptions",
    organizations_url: "https://api.github.com/users/anesdiaf/orgs",
    repos_url: "https://api.github.com/users/anesdiaf/repos",
    events_url: "https://api.github.com/users/anesdiaf/events{/privacy}",
    received_events_url: "https://api.github.com/users/anesdiaf/received_events",
    type: "User",
    site_admin: false,
    name: "Anes Diaf",
    company: null,
    blog: "https://www.anesdiaf.me",
    location: "Algeria",
    email: null,
    hireable: null,
    bio: "I'm a Web Developer, Javascript enthusiast and Problem solver.\r\n\r\n",
    twitter_username: "anesdiaf",
    public_repos: 6,
    public_gists: 0,
    followers: 2,
    following: 5,
    created_at: "2014-12-08T19:30:33Z",
    updated_at: "2022-01-18T04:34:33Z"
  };
